[project]
authors = ["orionhunts-ai <orion@oriondefensiveai.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "tradML_🔥"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
